azure_location             = "eastus"
environment                = "staging"
app_name                   = "ai20krosbag"
domain_name                = "staging.yourdomain.com"
backend_container_image    = "acrai20krosbagstaging.azurecr.io/backend:staging-latest"
frontend_container_image   = "acrai20krosbagstaging.azurecr.io/frontend:staging-latest"
backend_port               = 8000
frontend_port              = 3000
cpu                        = 0.25
memory                     = "0.5Gi"
cors_origins               = "https://staging.yourdomain.com,http://localhost:3000"
enable_persistent_storage  = true
acr_sku                    = "Basic"  # MVP cost optimization ($5/mo)
min_replicas               = 0        # Scale to zero when idle ($0 compute cost)
max_replicas               = 2
