environment    = "staging"
machine_type   = "e2-small"
backend_image  = "asia-docker.pkg.dev/ai20k-p077/backend:latest"
frontend_image = "asia-docker.pkg.dev/ai20k-p077/frontend:latest"
domain_name    = ""
cors_origins   = "http://localhost:3000"
